### ISSUE TITLE
Add Content Security Policy directive

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [hurradieweltgehtunter/landbot#2]
The app needs to load several external resources. Currently they get blocked:
```
Refused to load the script 'https://static.landbot.io/landbot-widget/landbot-widget-1.0.0.js?_=1557483037824' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

I tried to add a CSP like I found in this example: https://gitea.int.owncloud.com/consulting/sentry/src/branch/master/lib/Application.php#L91-L105

```
<?php
use OCP\AppFramework\App;
use OCP\AppFramework\Http\ContentSecurityPolicy;
use OCP\ILogger;
use OCP\IRequest;
use OCP\IUserSession;
use OCP\Security\IContentSecurityPolicyManager;

class Application extends App {

	public function __construct(array $urlParams = []) {

		$container = $this->getContainer();

		$policy = new OCP\AppFramework\Http\EmptyContentSecurityPolicy();
		$policy->addAllowedScriptDomain('landbot.io');
		\OC::$server->getContentSecurityPolicyManager()->addDefaultPolicy($policy);

	}

}
```

But this results in an internal server error. Currently I don't know what else to do.

**Comment by DeepDiver1975** [comment]
> But this results in an internal server error

there should be a log entry telling you why there is an internal server error.

internal server error is usually syntax error or something

**Comment by hurradieweltgehtunter** [comment]
log:
```
EmptyContentSecurityPolicy' not found
```
from line https://github.com/hurradieweltgehtunter/landbot/blob/723d763d7d23783e341361efc52fac3948597b1a/lib/Application.php#L18

**Comment by hurradieweltgehtunter** [comment]
current version adds the CSP but external JS gets still blocked (see static.landbot.io in screenshot)
![image](https://user-images.githubusercontent.com/16665512/57615826-ee8b1e80-757c-11e9-9d7f-bd01be542351.png)

**Comment by DeepDiver1975** [comment]
> current version adds the CSP but external JS gets still blocked (see static.landbot.io in screenshot)
> ![image](https://user-images.githubusercontent.com/16665512/57615826-ee8b1e80-757c-11e9-9d7f-bd01be542351.png)

this matches to https://github.com/hurradieweltgehtunter/landbot/blob/513fb0fbec788280aa42e07215f2125e2ba73235/lib/Application.php#L25



> $policy->addAllowedScriptDomain('landbot.io');

this should be used to address the error message

**Comment by hurradieweltgehtunter** [comment]
I dug a little deeper in the policy manager and figured it out. 
V1 coming soon.
Thanks for your help @DeepDiver1975
